version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/studentdb
      - DB_USER=postgres
      - DB_PASS=kardara
      - FRONT_END=http://localhost:3000
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - OAUTH_GOOGLE_ID=${OAUTH_GOOGLE_ID}
      - OAUTH_GOOGLE_SECRET=${OAUTH_GOOGLE_SECRET}
      - OAUTH_GITHUB_ID=${OAUTH_GITHUB_ID}
      - OAUTH_GITHUB_SECRET=${OAUTH_GITHUB_SECRET}
    depends_on:
      - db
    networks:
      - student-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=studentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kardara
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - student-network

volumes:
  postgres_data:

networks:
  student-network:
    driver: bridge